---
- hosts: test5 
  become: yes

  tasks:
#    - name: Ping
#      ping: 

    - name: Install required system packages
      apt: 
        update_cache: yes
        name: "{{ item }}"
        state: latest
      loop: 
           - "apt-transport-https"
           - "ca-certificates"
           - "curl"
           - "gnupg-agent" 
           - "software-properties-common"
           - "python3-pip"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
#      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
             
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu   groovy stable
        state: present

    - name: Update apt
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install Docker
      pip:
        name: docker     

    - name: Add user to Docker group
      shell: usermod -aG docker admturyk 


    - name: Pull Docker image
      docker_image:
        name: sturyk/itea-nodejs-app:1.1.3
        source: pull

    - name: Create docker containers
      docker_container:
        name: MyApp
        image: sturyk/itea-nodejs-app:1.1.3
        state: started
        ports:
          - "8081:8080"
          - "80:8080"


